# Generated by Django 5.1.7 on 2025-03-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_uploadedimage_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField()),
                ('date', models.TextField()),
                ('address', models.TextField()),
                ('items', models.TextField()),
                ('total', models.TextField()),
            ],
        ),
    ]
